Added legend
paulgavrikov/visualkeras pull request #3
Opened 2021-02-19 16:22 UTC by alejandroloda

Hi, I added a legend for the layered_view and some new colors.
![image](https://user-images.githubusercontent.com/56790857/108531405-9004df80-72ce-11eb-837e-fd604cc8885d.png)

2021-02-22 12:28 UTC, paulgavrikov requested changes
Hi @alejandroloda - thanks a lot for this great PR! Seems like the CI does not like you hardcoding arial ;) Could you look into this before I merge into master?

2021-02-22 12:28 UTC, paulgavrikov commented on visualkeras/layered.py
> +        font = ImageFont.truetype("arial.ttf", font_size)
This fails Travis CI

2021-02-23 22:32 UTC, alejandroloda commented
Looks like Travis can't open the font

2021-02-25 08:52 UTC, paulgavrikov commented
A quick google search tells me that you have to provide the full path to the font under Linux. And I believe I had similar issues when I tried to integrate fonts into visualkeras. I'd really want this module to be platform independant.
So, a simple solution would be to not provide the font parameter at all and let PIL use the default **or** to add another parameter to `layered_view` to pass an `ImageFont`. Would you be able to integrate those changes?

2021-02-25 11:59 UTC, alejandroloda commented
This change should works 
In case of not valid path for the font, the PIL default font will be load, but this one for now cannot be size change

2021-03-01 15:30 UTC, merged

2021-03-01 15:36 UTC, paulgavrikov commented
I have reverted the merge, since this code breaks examples/generate_examples.py with `legend=True`:

```
Traceback (most recent call last):
  File "/home/paulgavrikov/Coding/git/visualkeras/examples/generate_examples.py", line 2, in <module>
    from examples import vgg16
  File "/home/paulgavrikov/Coding/git/visualkeras/examples/vgg16.py", line 75, in <module>
    visualkeras.layered_view(model, to_file='../figures/vgg16_color_map.png',
  File "/home/paulgavrikov/Coding/git/visualkeras/visualkeras/layered.py", line 208, in layered_view
    draw_text.text((box.x2 + 10, box.y1 - (font_size / 2)), layer, font=font, fill='black')
  File "/home/paulgavrikov/.local/lib/python3.8/site-packages/PIL/ImageDraw.py", line 289, in text
    if self._multiline_check(text):
  File "/home/paulgavrikov/.local/lib/python3.8/site-packages/PIL/ImageDraw.py", line 264, in _multiline_check
    return split_character in text
TypeError: argument of type 'type' is not iterable

Process finished with exit code 1
```

2021-03-01 16:57 UTC, paulgavrikov commented
I also finally had some time to take a closer look. There are many hardcoded values that we have parameters for. Is your PR editable? If so I could push some changes later.

2021-03-03 12:44 UTC, alejandroloda commented
Sorry I'm pretty new with PR, so I'm not sure if it is or isn't editable, but I see on your commit that you implemented my changes with the params that you mentioned

I made a try, and looks like its works, but I miss to have more colors by default, if you consider it, these are what I used ["#ffd166", "#ef476f", "#f95c3a", "#f456d4", "#06d6a0", "#35d049", "#118ab2",  "#073b4c"]

But it's nice to have the legend working :)

2021-03-03 13:10 UTC, alejandroloda commented
I see too that you could just equal cube_size to text_height, to avoid big cubes with the default font (that I estimated that is an 8 size) (lines 184-186)

Before:
![image](https://user-images.githubusercontent.com/56790857/109808704-5a8db980-7c1f-11eb-8c9a-6f62f3be3bab.png)

After:
![image](https://user-images.githubusercontent.com/56790857/109808596-3c27be00-7c1f-11eb-89c7-65ba807c963e.png)

Also I see that due to use a set for layers_names, the order is loosen, so you could use a list instead and on line 191 do:
```` python
seen = set()
layer_names = [x for x in layer_names if not (x in seen or seen.add(x))]
````
![image](https://user-images.githubusercontent.com/56790857/109810621-aa6d8000-7c21-11eb-9424-ddde5614944e.png)

In this case don't forget to upgrade lines 51 (list for set) and 68 (append for add) to keep the compatibility

2021-03-05 10:05 UTC, paulgavrikov commented
There should be a checkbox when creating the PR to set it editable, but I am no expert either. Your changes are pretty much in the master. 
I'll change `cube_size` to `text_height` and I'll fix the legend order (with a slightly different trick) - thanks for the heads up! The proposed colors however don't really look nice on the VGG16 test (under /examples) and honestly, I don't have the time to play around with them for too long. I believe I got the original colors from a generator that attempted to maximize the distinguishability but I can no longer find the website. Anyways, I agree we should expand the number of colors in the wheel.

2021-03-05 13:10 UTC, alejandroloda commented
Pretty nice :)